import 'practice_formula_insertions.dart';
import 'practice_formula_key_models.dart';

// ── 极限与级数 ────────────────────────────────────────────────────────────────

final List<PracticeFormulaKeySpec> practiceFormulaUniversityMathKeys =
    <PracticeFormulaKeySpec>[
  // 极限符号
  _uniSymbol('varepsilon', 'ε', '艾普西隆', r'\varepsilon', usage: '极限定义中的任意正数 ε，用于 ε-δ 语言描述极限'),
  _uniSymbol('delta-lower', 'δ', '德尔塔', r'\delta', usage: '极限定义中的邻域半径 δ，用于 ε-δ 语言描述极限'),

  // 极限模板
  _uniTemplate(
    'lim-general',
    r'\lim_{\Box\to\Box}\Box',
    '一般极限',
    r'\lim_{{}\to{}}{}',
    '依次填写变量、趋近值和表达式',
    const CompositeFormulaInsertion(<String>[r'\lim_{', r'\to', r'}', '']),
  ),
  _uniTemplate(
    'lim-left',
    r'\lim_{\Box\to\Box^-}\Box',
    '左极限',
    r'\lim_{{}\to{}^-}{}',
    '依次填写变量、趋近点和表达式',
    const CompositeFormulaInsertion(<String>[r'\lim_{', r'\to', r'^-}', '']),
  ),
  _uniTemplate(
    'lim-right',
    r'\lim_{\Box\to\Box^+}\Box',
    '右极限',
    r'\lim_{{}\to{}^+}{}',
    '依次填写变量、趋近点和表达式',
    const CompositeFormulaInsertion(<String>[r'\lim_{', r'\to', r'^+}', '']),
  ),
  _uniTemplate(
    'lim-infinity',
    r'\lim_{\Box\to\infty}\Box',
    '无穷处极限',
    r'\lim_{{}\to\infty}{}',
    '依次填写变量和表达式',
    const CompositeFormulaInsertion(<String>[r'\lim_{', r'\to\infty}', '']),
  ),
  _uniTemplate(
    'sum-general',
    r'\sum_{\Box}^{\Box}\Box',
    '求和',
    r'\sum_{}^{}{}',
    '依次填写下限、上限和求和项',
    const CompositeFormulaInsertion(<String>[r'\sum_{', r'}^{', '}', '']),
  ),
  _uniTemplate(
    'sum-infinity',
    r'\sum_{n=1}^{\infty}\Box',
    '无穷级数',
    r'\sum_{n=1}^{\infty}{}',
    '填写级数通项',
    const CompositeFormulaInsertion(<String>[r'\sum_{n=1}^{\infty}', '']),
  ),
  _uniTemplate(
    'prod-general',
    r'\prod_{\Box}^{\Box}\Box',
    '连乘',
    r'\prod_{}^{}{}',
    '依次填写下限、上限和连乘项',
    const CompositeFormulaInsertion(<String>[r'\prod_{', r'}^{', '}', '']),
  ),

  // ── 微分 ──────────────────────────────────────────────────────────────────

  _uniSymbol('mathrm-d', 'd', '微分算子', r'\mathrm{d}', usage: '微分和积分中的直立体 d，区别于变量 d'),
  _uniTemplate(
    'derivative-first',
    r'\frac{d\Box}{d\Box}',
    '一阶导数',
    r'\frac{\mathrm{d}{}}{\mathrm{d}{}}',
    '依次填写分子变量和分母变量',
    const CompositeFormulaInsertion(<String>[
      r'\frac{\mathrm{d}{',
      r'}}{\mathrm{d}{',
      r'}}',
    ]),
  ),
  _uniTemplate(
    'derivative-nth',
    r'\frac{d^n\Box}{d\Box^n}',
    'n 阶导数',
    r'\frac{\mathrm{d}^{n}{}}{\mathrm{d}{}^{n}}',
    '依次填写函数和变量',
    const CompositeFormulaInsertion(<String>[
      r'\frac{\mathrm{d}^{n}{',
      r'}}{\mathrm{d}{',
      r'}^{n}}',
    ]),
  ),
  _uniSymbol('partial', '∂', '偏导符号', r'\partial', usage: '用于多元函数对某一个变量求导'),
  _uniTemplate(
    'partial-first',
    r'\frac{\partial\Box}{\partial\Box}',
    '一阶偏导数',
    r'\frac{\partial{}}{\partial{}}',
    '依次填写函数和变量',
    const CompositeFormulaInsertion(<String>[
      r'\frac{\partial{',
      r'}}{\partial{',
      r'}}',
    ]),
  ),
  _uniTemplate(
    'partial-mixed',
    r'\frac{\partial^2\Box}{\partial\Box\partial\Box}',
    '二阶混合偏导数',
    r'\frac{\partial^{2}{}}{\partial{}\partial{}}',
    '依次填写函数和两个变量',
    const CompositeFormulaInsertion(<String>[
      r'\frac{\partial^{2}{',
      r'}}{\partial{',
      r'}\partial{',
      r'}}',
    ]),
  ),
  _uniSymbol('nabla', '∇', 'Nabla 算子', r'\nabla', usage: '用于表示梯度、散度、旋度等向量运算'),
  _uniTemplate(
    'gradient',
    r'\nabla\Box',
    '梯度',
    r'\nabla{}',
    '填写标量场',
    const CompositeFormulaInsertion(<String>[r'\nabla{', '}']),
  ),
  _uniTemplate(
    'divergence',
    r'\nabla\cdot\Box',
    '散度',
    r'\nabla\cdot{}',
    '填写向量场',
    const CompositeFormulaInsertion(<String>[r'\nabla\cdot{', '}']),
  ),
  _uniTemplate(
    'curl',
    r'\nabla\times\Box',
    '旋度',
    r'\nabla\times{}',
    '填写向量场',
    const CompositeFormulaInsertion(<String>[r'\nabla\times{', '}']),
  ),
  _uniTemplate(
    'laplacian',
    r'\nabla^2\Box',
    '拉普拉斯算子',
    r'\nabla^{2}{}',
    '填写函数',
    const CompositeFormulaInsertion(<String>[r'\nabla^{2}{', '}']),
  ),

  // ── 积分 ──────────────────────────────────────────────────────────────────

  _uniTemplate(
    'integral-indef',
    r'\int\Box\,d\Box',
    '不定积分',
    r'\int{}\,\mathrm{d}{}',
    '依次填写被积式和积分变量',
    const CompositeFormulaInsertion(<String>[
      r'\int{',
      r'}\,\mathrm{d}{',
      '}',
    ]),
  ),
  _uniTemplate(
    'integral-def',
    r'\int_{\Box}^{\Box}\Box\,d\Box',
    '定积分',
    r'\int_{}^{}{}\,\mathrm{d}',
    '依次填写下限、上限、被积式和积分变量',
    const CompositeFormulaInsertion(<String>[
      r'\int_{',
      r'}^{',
      r'}{',
      r'}\,\mathrm{d}{',
      '}',
    ]),
  ),
  _uniTemplate(
    'integral-improper',
    r'\int_{\Box}^{\infty}\Box\,d\Box',
    '反常积分',
    r'\int_{}^{\infty}{}\,\mathrm{d}{}',
    '依次填写下限、被积式和积分变量',
    const CompositeFormulaInsertion(<String>[
      r'\int_{',
      r'}^{\infty}{',
      r'}\,\mathrm{d}{',
      '}',
    ]),
  ),
  _uniTemplate(
    'integral-double',
    r'\iint_{\Box}\Box\,d\Box',
    '二重积分',
    r'\iint_{}{}\,\mathrm{d}{}',
    '依次填写积分区域、被积式和面积元',
    const CompositeFormulaInsertion(<String>[
      r'\iint_{',
      r'}{',
      r'}\,\mathrm{d}{',
      '}',
    ]),
  ),
  _uniTemplate(
    'integral-triple',
    r'\iiint_{\Box}\Box\,d\Box',
    '三重积分',
    r'\iiint_{}{}\,\mathrm{d}{}',
    '依次填写积分区域、被积式和体积元',
    const CompositeFormulaInsertion(<String>[
      r'\iiint_{',
      r'}{',
      r'}\,\mathrm{d}{',
      '}',
    ]),
  ),
  _uniTemplate(
    'integral-line',
    r'\int_{L}\Box\,ds',
    '曲线积分',
    r'\int_{L}{}\,\mathrm{d}s',
    '填写被积式',
    const CompositeFormulaInsertion(<String>[r'\int_{L}{', r'}\,\mathrm{d}s']),
  ),
  _uniTemplate(
    'integral-closed',
    r'\oint_{L}\Box\,d\Box',
    '闭合曲线积分',
    r'\oint_{L}{}\,\mathrm{d}{}',
    '依次填写被积式和积分变量',
    const CompositeFormulaInsertion(<String>[
      r'\oint_{L}{',
      r'}\,\mathrm{d}{',
      '}',
    ]),
  ),
  _uniTemplate(
    'integral-surface',
    r'\iint_{S}\Box\,dS',
    '曲面积分',
    r'\iint_{S}{}\,\mathrm{d}S',
    '填写被积式',
    const CompositeFormulaInsertion(<String>[
      r'\iint_{S}{',
      r'}\,\mathrm{d}S',
    ]),
  ),

  // ── 矩阵与线性代数 ────────────────────────────────────────────────────────

  _uniTemplate(
    'matrix-2x2',
    r'\begin{bmatrix}\Box&\Box\\\Box&\Box\end{bmatrix}',
    '2×2 矩阵',
    r'\begin{bmatrix}{}&{}\\{}&{}\end{bmatrix}',
    '按行从左到右依次填写四个元素',
    const CompositeFormulaInsertion(<String>[
      r'\begin{bmatrix}{',
      r'}&{',
      r'}\\{',
      r'}&{',
      r'}\end{bmatrix}',
    ]),
  ),
  _uniTemplate(
    'matrix-3x3',
    r'\begin{bmatrix}\Box&\Box&\Box\\\Box&\Box&\Box\\\Box&\Box&\Box\end{bmatrix}',
    '3×3 矩阵',
    r'\begin{bmatrix}{}&{}&{}\\{}&{}&{}\\{}&{}&{}\end{bmatrix}',
    '按行从左到右依次填写九个元素',
    const CompositeFormulaInsertion(<String>[
      r'\begin{bmatrix}{',
      r'}&{',
      r'}&{',
      r'}\\{',
      r'}&{',
      r'}&{',
      r'}\\{',
      r'}&{',
      r'}&{',
      r'}\end{bmatrix}',
    ]),
  ),
  _uniTemplate(
    'det-2x2',
    r'\begin{vmatrix}\Box&\Box\\\Box&\Box\end{vmatrix}',
    '2×2 行列式',
    r'\begin{vmatrix}{}&{}\\{}&{}\end{vmatrix}',
    '按行从左到右依次填写四个元素',
    const CompositeFormulaInsertion(<String>[
      r'\begin{vmatrix}{',
      r'}&{',
      r'}\\{',
      r'}&{',
      r'}\end{vmatrix}',
    ]),
  ),
  _uniTemplate(
    'det-func',
    r'\det\left(\Box\right)',
    '行列式函数',
    r'\det\left({}\right)',
    '填写矩阵',
    const CompositeFormulaInsertion(<String>[r'\det\left({', r'}\right)']),
  ),
  _uniTemplate(
    'transpose',
    r'\Box^T',
    '转置矩阵',
    r'{}^{\mathsf{T}}',
    '先输入矩阵名再点击此键',
    const CompositeFormulaInsertion(<String>[r'^{\mathsf{T}', '}']),
  ),
  _uniTemplate(
    'inverse',
    r'\Box^{-1}',
    '逆矩阵',
    r'{}^{-1}',
    '先输入矩阵名再点击此键',
    const CompositeFormulaInsertion(<String>[r'^{-1', '}']),
  ),
  _uniTemplate(
    'rank',
    r'\text{rank}(\Box)',
    '矩阵的秩',
    r'\operatorname{rank}\left({}\right)',
    '填写矩阵',
    const CompositeFormulaInsertion(<String>[
      r'\operatorname{rank}\left({',
      r'}\right)',
    ]),
  ),
  _uniTemplate(
    'trace',
    r'\text{tr}(\Box)',
    '矩阵的迹',
    r'\operatorname{tr}\left({}\right)',
    '填写矩阵',
    const CompositeFormulaInsertion(<String>[
      r'\operatorname{tr}\left({',
      r'}\right)',
    ]),
  ),
  _uniTemplate(
    'norm-matrix',
    r'\left\lVert\Box\right\rVert',
    '范数',
    r'\left\lVert{}\right\rVert',
    '填写向量或矩阵',
    const CompositeFormulaInsertion(<String>[
      r'\left\lVert{',
      r'}\right\rVert',
    ]),
  ),
  _uniTemplate(
    'inner-product',
    r'\left\langle\Box,\Box\right\rangle',
    '内积',
    r'\left\langle{},{}\right\rangle',
    '依次填写两个向量',
    const CompositeFormulaInsertion(<String>[
      r'\left\langle{',
      r'},{',
      r'}\right\rangle',
    ]),
  ),
];

PracticeFormulaKeySpec _uniSymbol(
  String id,
  String label,
  String name,
  String latex, {
  String? usage,
}) => PracticeFormulaKeySpec.catalog(
  id: 'uni-$id',
  label: label,
  name: name,
  semanticLabel: name,
  expectedLatex: latex,
  kind: PracticeFormulaKeyKind.symbol,
  section: PracticeFormulaSection.mathUniversity,
  placement: PracticeFormulaKeyPlacement.sectionGrid,
  usage: usage ?? '输入$name',
  insertion: LeafFormulaInsertion(latex.startsWith(r'\') ? '$latex ' : latex),
);

PracticeFormulaKeySpec _uniTemplate(
  String id,
  String label,
  String name,
  String expectedLatex,
  String usage,
  PracticeFormulaInsertion insertion,
) => PracticeFormulaKeySpec.catalog(
  id: 'uni-$id',
  label: label,
  name: name,
  semanticLabel: '插入$name模板',
  expectedLatex: expectedLatex,
  kind: PracticeFormulaKeyKind.template,
  section: PracticeFormulaSection.mathUniversity,
  placement: PracticeFormulaKeyPlacement.sectionGrid,
  usage: usage,
  insertion: insertion,
  isTexLabel: true,
);
