import 'practice_formula_insertions.dart';
import 'practice_formula_key_models.dart';

const List<PracticeFormulaArgument> _braces = <PracticeFormulaArgument>[
  PracticeFormulaArgument.braces,
];

/// 固定数字区是数字和四则运算符的唯一主位置，正式目录不再重复这些键。
const List<PracticeFormulaKeySpec> practiceFormulaNumericKeys =
    <PracticeFormulaKeySpec>[
      PracticeFormulaKeySpec.catalog(
        id: '7',
        label: '7',
        name: '数字 7',
        semanticLabel: '数字 7',
        expectedLatex: '7',
        kind: PracticeFormulaKeyKind.character,
        section: PracticeFormulaSection.lettersAndNumbers,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入数字 7',
        insertion: LeafFormulaInsertion('7'),
      ),
      PracticeFormulaKeySpec.catalog(
        id: '8',
        label: '8',
        name: '数字 8',
        semanticLabel: '数字 8',
        expectedLatex: '8',
        kind: PracticeFormulaKeyKind.character,
        section: PracticeFormulaSection.lettersAndNumbers,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入数字 8',
        insertion: LeafFormulaInsertion('8'),
      ),
      PracticeFormulaKeySpec.catalog(
        id: '9',
        label: '9',
        name: '数字 9',
        semanticLabel: '数字 9',
        expectedLatex: '9',
        kind: PracticeFormulaKeyKind.character,
        section: PracticeFormulaSection.lettersAndNumbers,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入数字 9',
        insertion: LeafFormulaInsertion('9'),
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'divide',
        label: '÷',
        name: '除号',
        semanticLabel: '除号',
        expectedLatex: r'\div',
        kind: PracticeFormulaKeyKind.symbol,
        section: PracticeFormulaSection.commonSymbols,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入除法运算',
        insertion: LeafFormulaInsertion(r'\div '),
      ),
      PracticeFormulaKeySpec.catalog(
        id: '4',
        label: '4',
        name: '数字 4',
        semanticLabel: '数字 4',
        expectedLatex: '4',
        kind: PracticeFormulaKeyKind.character,
        section: PracticeFormulaSection.lettersAndNumbers,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入数字 4',
        insertion: LeafFormulaInsertion('4'),
      ),
      PracticeFormulaKeySpec.catalog(
        id: '5',
        label: '5',
        name: '数字 5',
        semanticLabel: '数字 5',
        expectedLatex: '5',
        kind: PracticeFormulaKeyKind.character,
        section: PracticeFormulaSection.lettersAndNumbers,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入数字 5',
        insertion: LeafFormulaInsertion('5'),
      ),
      PracticeFormulaKeySpec.catalog(
        id: '6',
        label: '6',
        name: '数字 6',
        semanticLabel: '数字 6',
        expectedLatex: '6',
        kind: PracticeFormulaKeyKind.character,
        section: PracticeFormulaSection.lettersAndNumbers,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入数字 6',
        insertion: LeafFormulaInsertion('6'),
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'multiply',
        label: '×',
        name: '乘号',
        semanticLabel: '乘号',
        expectedLatex: r'\times',
        kind: PracticeFormulaKeyKind.symbol,
        section: PracticeFormulaSection.commonSymbols,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入乘法运算',
        insertion: LeafFormulaInsertion(r'\times '),
      ),
      PracticeFormulaKeySpec.catalog(
        id: '1',
        label: '1',
        name: '数字 1',
        semanticLabel: '数字 1',
        expectedLatex: '1',
        kind: PracticeFormulaKeyKind.character,
        section: PracticeFormulaSection.lettersAndNumbers,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入数字 1',
        insertion: LeafFormulaInsertion('1'),
      ),
      PracticeFormulaKeySpec.catalog(
        id: '2',
        label: '2',
        name: '数字 2',
        semanticLabel: '数字 2',
        expectedLatex: '2',
        kind: PracticeFormulaKeyKind.character,
        section: PracticeFormulaSection.lettersAndNumbers,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入数字 2',
        insertion: LeafFormulaInsertion('2'),
      ),
      PracticeFormulaKeySpec.catalog(
        id: '3',
        label: '3',
        name: '数字 3',
        semanticLabel: '数字 3',
        expectedLatex: '3',
        kind: PracticeFormulaKeyKind.character,
        section: PracticeFormulaSection.lettersAndNumbers,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入数字 3',
        insertion: LeafFormulaInsertion('3'),
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'minus',
        label: '−',
        name: '减号',
        semanticLabel: '减号',
        expectedLatex: '-',
        kind: PracticeFormulaKeyKind.symbol,
        section: PracticeFormulaSection.commonSymbols,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入减法或负号',
        insertion: LeafFormulaInsertion('-'),
      ),
      PracticeFormulaKeySpec.catalog(
        id: '0',
        label: '0',
        name: '数字 0',
        semanticLabel: '数字 0',
        expectedLatex: '0',
        kind: PracticeFormulaKeyKind.character,
        section: PracticeFormulaSection.lettersAndNumbers,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入数字 0',
        insertion: LeafFormulaInsertion('0'),
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'decimal',
        label: '.',
        name: '小数点',
        semanticLabel: '小数点',
        expectedLatex: '.',
        kind: PracticeFormulaKeyKind.character,
        section: PracticeFormulaSection.lettersAndNumbers,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入小数点',
        insertion: LeafFormulaInsertion('.'),
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'plus',
        label: '+',
        name: '加号',
        semanticLabel: '加号',
        expectedLatex: '+',
        kind: PracticeFormulaKeyKind.symbol,
        section: PracticeFormulaSection.commonSymbols,
        placement: PracticeFormulaKeyPlacement.fixedPad,
        usage: '输入加法运算',
        insertion: LeafFormulaInsertion('+'),
      ),
    ];

const List<PracticeFormulaKeySpec> _commonSymbolKeys = <PracticeFormulaKeySpec>[
  PracticeFormulaKeySpec.catalog(
    id: 'plus-minus',
    label: '±',
    name: '正负号',
    semanticLabel: '正负号',
    expectedLatex: r'\pm',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '表示正负两种取值',
    insertion: LeafFormulaInsertion(r'\pm '),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'dot-multiply',
    label: '·',
    name: '点乘号',
    semanticLabel: '点乘号',
    expectedLatex: r'\cdot',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '输入省略乘号的点乘形式',
    insertion: LeafFormulaInsertion(r'\cdot '),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'slash',
    label: '/',
    name: '斜杠',
    semanticLabel: '斜杠',
    expectedLatex: '/',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '输入行内比值或单位分隔',
    insertion: LeafFormulaInsertion('/'),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'equals',
    label: '=',
    name: '等号',
    semanticLabel: '等号',
    expectedLatex: '=',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '表示相等关系',
    insertion: LeafFormulaInsertion('='),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'not-equal',
    label: '≠',
    name: '不等号',
    semanticLabel: '不等于',
    expectedLatex: r'\ne',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '表示不相等关系',
    insertion: LeafFormulaInsertion(r'\ne '),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'approx',
    label: '≈',
    name: '约等号',
    semanticLabel: '约等于',
    expectedLatex: r'\approx',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '表示近似相等',
    insertion: LeafFormulaInsertion(r'\approx '),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'less',
    label: '<',
    name: '小于号',
    semanticLabel: '小于',
    expectedLatex: '<',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '表示小于关系',
    insertion: LeafFormulaInsertion('<'),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'greater',
    label: '>',
    name: '大于号',
    semanticLabel: '大于',
    expectedLatex: '>',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '表示大于关系',
    insertion: LeafFormulaInsertion('>'),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'less-equal',
    label: '≤',
    name: '小于等于号',
    semanticLabel: '小于等于',
    expectedLatex: r'\le',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '表示小于或等于',
    insertion: LeafFormulaInsertion(r'\le '),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'greater-equal',
    label: '≥',
    name: '大于等于号',
    semanticLabel: '大于等于',
    expectedLatex: r'\ge',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '表示大于或等于',
    insertion: LeafFormulaInsertion(r'\ge '),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'percent',
    label: '%',
    name: '百分号',
    semanticLabel: '百分号',
    expectedLatex: r'\%',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '表示百分数',
    insertion: LeafFormulaInsertion(r'\%'),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'degree',
    label: '°',
    name: '度数符号',
    semanticLabel: '度数符号',
    expectedLatex: r'^{\circ}',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '表示角度或温度中的度',
    insertion: LeafFormulaInsertion(r'^{\circ}'),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'comma',
    label: ',',
    name: '逗号',
    semanticLabel: '逗号',
    expectedLatex: ',',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '分隔坐标或多个答案',
    insertion: LeafFormulaInsertion(','),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'semicolon',
    label: ';',
    name: '分号',
    semanticLabel: '分号',
    expectedLatex: ';',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '分隔条件或多段表达式',
    insertion: LeafFormulaInsertion(';'),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'factorial',
    label: '!',
    name: '阶乘符号',
    semanticLabel: '阶乘',
    expectedLatex: '!',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '表示阶乘',
    insertion: LeafFormulaInsertion('!'),
  ),
  PracticeFormulaKeySpec.catalog(
    id: 'ellipsis',
    label: '⋯',
    name: '省略号',
    semanticLabel: '数学省略号',
    expectedLatex: r'\cdots',
    kind: PracticeFormulaKeyKind.symbol,
    section: PracticeFormulaSection.commonSymbols,
    placement: PracticeFormulaKeyPlacement.sectionGrid,
    usage: '表示数列或运算项的省略',
    insertion: LeafFormulaInsertion(r'\cdots '),
  ),
];

const PracticeFormulaKeySpec practiceFormulaScientificNotationKey =
    PracticeFormulaKeySpec.catalog(
      id: 'scientific-notation',
      label: r'\Box\times10^{\Box}',
      name: '科学记数法',
      semanticLabel: '插入科学记数法模板',
      expectedLatex: r'{}\times10^{}',
      kind: PracticeFormulaKeyKind.template,
      section: PracticeFormulaSection.commonTemplates,
      placement: PracticeFormulaKeyPlacement.sectionGrid,
      usage: '按“系数、指数”的顺序填写科学记数法',
      insertion: CompositeFormulaInsertion(<String>['', r'\times10^{', '}']),
      isTexLabel: true,
    );

const List<PracticeFormulaKeySpec> _commonTemplateKeys =
    <PracticeFormulaKeySpec>[
      PracticeFormulaKeySpec.catalog(
        id: 'fraction',
        label: r'\frac{\Box}{\Box}',
        name: '分式',
        semanticLabel: '插入分式',
        expectedLatex: r'\frac{}{}',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '依次填写分子和分母',
        insertion: FunctionFormulaInsertion(r'\frac', <PracticeFormulaArgument>[
          PracticeFormulaArgument.braces,
          PracticeFormulaArgument.braces,
        ]),
        isTexLabel: true,
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'power',
        label: r'\Box^{\Box}',
        name: '任意次幂',
        semanticLabel: '插入任意次幂',
        expectedLatex: r'^{}',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '先输入底数，再填写指数',
        insertion: FunctionFormulaInsertion('^', _braces),
        isTexLabel: true,
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'square',
        label: r'\Box^2',
        name: '平方',
        semanticLabel: '插入平方',
        expectedLatex: r'^{2}',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '先输入底数，再添加平方',
        insertion: FixedExponentFormulaInsertion('2'),
        isTexLabel: true,
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'cube',
        label: r'\Box^3',
        name: '立方',
        semanticLabel: '插入立方',
        expectedLatex: r'^{3}',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '先输入底数，再添加立方',
        insertion: FixedExponentFormulaInsertion('3'),
        isTexLabel: true,
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'subscript',
        label: r'\Box_{\Box}',
        name: '下标',
        semanticLabel: '插入下标',
        expectedLatex: r'_{}',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '填写变量下标',
        insertion: FunctionFormulaInsertion('_', _braces),
        isTexLabel: true,
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'sub-superscript',
        label: r'\Box_{\Box}^{\Box}',
        name: '上下标',
        semanticLabel: '插入上下标',
        expectedLatex: r'_{}^{}',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '依次填写下标和上标',
        insertion: SubSuperscriptFormulaInsertion(),
        isTexLabel: true,
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'sqrt',
        label: r'\sqrt{\Box}',
        name: '平方根',
        semanticLabel: '插入平方根',
        expectedLatex: r'\sqrt{}',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '填写被开方数',
        insertion: FunctionFormulaInsertion(r'\sqrt', _braces),
        isTexLabel: true,
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'nth-root',
        label: r'\sqrt[\Box]{\Box}',
        name: 'n 次根',
        semanticLabel: '插入 n 次根',
        expectedLatex: r'\sqrt[]{}',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '依次填写根指数和被开方数',
        insertion: FunctionFormulaInsertion(r'\sqrt', <PracticeFormulaArgument>[
          PracticeFormulaArgument.brackets,
          PracticeFormulaArgument.braces,
        ]),
        isTexLabel: true,
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'parentheses',
        label: r'\left(\Box\right)',
        name: '圆括号',
        semanticLabel: '插入圆括号',
        expectedLatex: r'\left(\right)',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '在括号内填写表达式',
        insertion: PairFormulaInsertion(r'\left(', r'\right)'),
        isTexLabel: true,
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'brackets',
        label: r'\left[\Box\right]',
        name: '方括号',
        semanticLabel: '插入方括号',
        expectedLatex: r'\left[\right]',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '在方括号内填写表达式',
        insertion: PairFormulaInsertion(r'\left[', r'\right]'),
        isTexLabel: true,
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'braces',
        label: r'\left\{\Box\right\}',
        name: '花括号',
        semanticLabel: '插入花括号',
        expectedLatex: r'\left\{\right\}',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '在花括号内填写表达式',
        insertion: PairFormulaInsertion(r'\left\{', r'\right\}'),
        isTexLabel: true,
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'absolute',
        label: r'\left\lvert\Box\right\rvert',
        name: '绝对值',
        semanticLabel: '插入绝对值',
        expectedLatex: r'\left\lvert\right\rvert',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '填写绝对值中的表达式',
        insertion: PairFormulaInsertion(r'\left\lvert', r'\right\rvert'),
        isTexLabel: true,
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'overline',
        label: r'\overline{\Box}',
        name: '上划线',
        semanticLabel: '插入上划线',
        expectedLatex: r'\overline{}',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '给表达式添加上划线',
        insertion: FunctionFormulaInsertion(r'\overline', _braces),
        isTexLabel: true,
      ),
      PracticeFormulaKeySpec.catalog(
        id: 'vector',
        label: r'\vec{\Box}',
        name: '向量',
        semanticLabel: '插入向量',
        expectedLatex: r'\vec{}',
        kind: PracticeFormulaKeyKind.template,
        section: PracticeFormulaSection.commonTemplates,
        placement: PracticeFormulaKeyPlacement.sectionGrid,
        usage: '填写向量名称',
        insertion: FunctionFormulaInsertion(r'\vec', _braces),
        isTexLabel: true,
      ),
      practiceFormulaScientificNotationKey,
    ];

/// 常用类的正式二级目录，不包含固定数字区。
const Map<PracticeFormulaSection, List<PracticeFormulaKeySpec>>
practiceFormulaCommonSectionKeys =
    <PracticeFormulaSection, List<PracticeFormulaKeySpec>>{
      PracticeFormulaSection.commonSymbols: _commonSymbolKeys,
      PracticeFormulaSection.commonTemplates: _commonTemplateKeys,
    };

/// 生成字母页；π、α、β、θ随字母展示，但数字仍只留在固定数字区。
List<PracticeFormulaKeySpec> practiceFormulaLetterAndNumberKeys({
  required bool uppercase,
}) {
  final letters = List<PracticeFormulaKeySpec>.generate(26, (index) {
    final lowercase = String.fromCharCode('a'.codeUnitAt(0) + index);
    final value = uppercase ? lowercase.toUpperCase() : lowercase;
    return PracticeFormulaKeySpec.catalog(
      id: 'letter-$lowercase',
      label: value,
      name: '字母 $value',
      semanticLabel: '字母 $value',
      expectedLatex: value,
      kind: PracticeFormulaKeyKind.character,
      section: PracticeFormulaSection.lettersAndNumbers,
      placement: PracticeFormulaKeyPlacement.sectionGrid,
      usage: '输入变量 $value',
      insertion: LeafFormulaInsertion(value),
    );
  }, growable: true);
  return letters..addAll(const <PracticeFormulaKeySpec>[
    PracticeFormulaKeySpec.catalog(
      id: 'pi',
      label: 'π',
      name: '圆周率',
      semanticLabel: '圆周率 pi',
      expectedLatex: r'\pi',
      kind: PracticeFormulaKeyKind.symbol,
      section: PracticeFormulaSection.lettersAndNumbers,
      placement: PracticeFormulaKeyPlacement.sectionGrid,
      usage: '输入圆周率符号',
      insertion: LeafFormulaInsertion(r'\pi '),
    ),
    PracticeFormulaKeySpec.catalog(
      id: 'alpha',
      label: 'α',
      name: '希腊字母 alpha',
      semanticLabel: '希腊字母 alpha',
      expectedLatex: r'\alpha',
      kind: PracticeFormulaKeyKind.character,
      section: PracticeFormulaSection.lettersAndNumbers,
      placement: PracticeFormulaKeyPlacement.sectionGrid,
      usage: '输入常用角或系数 α',
      insertion: LeafFormulaInsertion(r'\alpha '),
    ),
    PracticeFormulaKeySpec.catalog(
      id: 'beta',
      label: 'β',
      name: '希腊字母 beta',
      semanticLabel: '希腊字母 beta',
      expectedLatex: r'\beta',
      kind: PracticeFormulaKeyKind.character,
      section: PracticeFormulaSection.lettersAndNumbers,
      placement: PracticeFormulaKeyPlacement.sectionGrid,
      usage: '输入常用角或系数 β',
      insertion: LeafFormulaInsertion(r'\beta '),
    ),
    PracticeFormulaKeySpec.catalog(
      id: 'theta',
      label: 'θ',
      name: '希腊字母 theta',
      semanticLabel: '希腊字母 theta',
      expectedLatex: r'\theta',
      kind: PracticeFormulaKeyKind.character,
      section: PracticeFormulaSection.lettersAndNumbers,
      placement: PracticeFormulaKeyPlacement.sectionGrid,
      usage: '输入常用角 θ',
      insertion: LeafFormulaInsertion(r'\theta '),
    ),
  ]);
}

/// 迁移期兼容入口；正式字母标签另含 π、α、β、θ 四个常用字符。
List<PracticeFormulaKeySpec> practiceFormulaAlphabetKeys({
  required bool uppercase,
}) => practiceFormulaLetterAndNumberKeys(
  uppercase: uppercase,
).take(26).toList(growable: false);
